/// Production seed geography + landmark catalog (Saudi tourism).
class ProductionSeedGeo {
  const ProductionSeedGeo({
    required this.countryId,
    required this.countryName,
    required this.countryDesc,
    required this.regions,
  });

  final String countryId;
  final String countryName;
  final String countryDesc;
  final List<ProductionSeedRegion> regions;
}

class ProductionSeedRegion {
  const ProductionSeedRegion({
    required this.id,
    required this.name,
    required this.cities,
  });

  final String id;
  final String name;
  final List<ProductionSeedCity> cities;
}

class ProductionSeedCity {
  const ProductionSeedCity({
    required this.id,
    required this.name,
  });

  final String id;
  final String name;
}

class ProductionSeedLandmark {
  const ProductionSeedLandmark({
    required this.id,
    required this.name,
    required this.description,
    required this.regionId,
    required this.cityId,
    required this.lat,
    required this.lng,
    required this.address,
    required this.img1,
    this.img2,
    this.img3,
    this.isPartner = false,
    this.isMosque = false,
    this.isFood = true,
    this.isRestroom = true,
    this.rate = 4.6,
    this.sortOrder = 0,
    this.daysAgo = 180,
    this.category = 'معلم سياحي',
    this.phone = '+966112345678',
  });

  final String id;
  final String name;
  final String description;
  final String regionId;
  final String cityId;
  final double lat;
  final double lng;
  final String address;
  final String img1;
  final String? img2;
  final String? img3;
  final bool isPartner;
  final bool isMosque;
  final bool isFood;
  final bool isRestroom;
  final double rate;
  final int sortOrder;
  final int daysAgo;
  final String category;
  final String phone;
}

/// Full catalog used by [AdminProductionLandmarkSeed].
class AdminProductionSeedCatalog {
  AdminProductionSeedCatalog._();

  static const countryId = 'saudi_arabia';
  static const countryName = 'المملكة العربية السعودية';
  static const countryDesc =
      'وجهة سياحية عالمية تجمع بين التراث العريق والمشاريع الحديثة ضمن رؤية 2030.';

  static const geo = ProductionSeedGeo(
    countryId: countryId,
    countryName: countryName,
    countryDesc: countryDesc,
    regions: [
      ProductionSeedRegion(
        id: 'region_riyadh',
        name: 'منطقة الرياض',
        cities: [
          ProductionSeedCity(id: 'city_riyadh', name: 'الرياض'),
          ProductionSeedCity(id: 'city_diria', name: 'الدرعية'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_makkah',
        name: 'منطقة مكة المكرمة',
        cities: [
          ProductionSeedCity(id: 'city_makkah', name: 'مكة المكرمة'),
          ProductionSeedCity(id: 'city_jeddah', name: 'جدة'),
          ProductionSeedCity(id: 'city_taif', name: 'الطائف'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_madinah',
        name: 'منطقة المدينة المنورة',
        cities: [
          ProductionSeedCity(id: 'city_madinah', name: 'المدينة المنورة'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_eastern',
        name: 'المنطقة الشرقية',
        cities: [
          ProductionSeedCity(id: 'city_dammam', name: 'الدمام'),
          ProductionSeedCity(id: 'city_alkhobar', name: 'الخبر'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_asir',
        name: 'منطقة عسير',
        cities: [
          ProductionSeedCity(id: 'city_abha', name: 'أبها'),
          ProductionSeedCity(id: 'city_rijal', name: 'رجال ألمع'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_alula',
        name: 'منطقة العلا',
        cities: [
          ProductionSeedCity(id: 'city_alula', name: 'العلا'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_tabuk',
        name: 'منطقة تبوك',
        cities: [
          ProductionSeedCity(id: 'city_tabuk', name: 'تبوك'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_hail',
        name: 'منطقة حائل',
        cities: [
          ProductionSeedCity(id: 'city_hail', name: 'حائل'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_jazan',
        name: 'منطقة جازان',
        cities: [
          ProductionSeedCity(id: 'city_jazan', name: 'جازان'),
          ProductionSeedCity(id: 'city_farsan', name: 'فرسان'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_najran',
        name: 'منطقة نجران',
        cities: [
          ProductionSeedCity(id: 'city_najran', name: 'نجران'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_qassim',
        name: 'منطقة القصيم',
        cities: [
          ProductionSeedCity(id: 'city_buraidah', name: 'بريدة'),
          ProductionSeedCity(id: 'city_unaizah', name: 'عنيزة'),
        ],
      ),
      ProductionSeedRegion(
        id: 'region_ahsa',
        name: 'منطقة الأحساء',
        cities: [
          ProductionSeedCity(id: 'city_hofuf', name: 'الهفوف'),
          ProductionSeedCity(id: 'city_almubarraz', name: 'المبرز'),
        ],
      ),
    ],
  );

  static const customerNames = [
    'أحمد العتيبي',
    'سارة القحطاني',
    'محمد الشهري',
    'نورة الدوسري',
    'فهد الحربي',
    'ريم السبيعي',
    'خالد المطيري',
    'لينا الزهراني',
    'عبدالله الغامدي',
    'هند العنزي',
    'يوسف البلوي',
    'مها الأحمدي',
  ];

  static const landmarks = <ProductionSeedLandmark>[
    ProductionSeedLandmark(
      id: 'mkan_diria',
      name: 'حي الطريف التاريخي',
      description:
          'موقع تراث عالمي في الدرعية يعكس تاريخ الدولة السعودية الأولى. يضم قصوراً طينية ومسارات مشاة ومتاحف تفاعلية مناسبة للعائلات والسياح.',
      regionId: 'region_riyadh',
      cityId: 'city_diria',
      lat: 24.7357,
      lng: 46.5725,
      address: 'الدرعية، منطقة الرياض',
      img1: 'https://images.unsplash.com/photo-1586728122893-0b47a745f769?w=1200&q=80',
      img2: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
      isMosque: true,
      rate: 4.9,
      sortOrder: 1,
      daysAgo: 340,
      isPartner: true,
      phone: '+966115665000',
    ),
    ProductionSeedLandmark(
      id: 'mkan_kingdom_tower',
      name: 'برج المملكة — سكاي بريدج',
      description:
          'أيقونة الرياض الحديثة بإطلالة بانورامية من جسر السماء. يوفر تجربة مشاهدة المدينة ومطاعم راقية ومناسب للزيارات المسائية.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.7113,
      lng: 46.6743,
      address: 'طريق الملك فهد، الرياض',
      img1: 'https://images.unsplash.com/photo-1586728122893-0b47a745f769?w=1200&q=80',
      img2: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.7,
      sortOrder: 2,
      daysAgo: 320,
    ),
    ProductionSeedLandmark(
      id: 'mkan_boulevard',
      name: 'بوليفارد الرياض',
      description:
          'وجهة ترفيهية متكاملة تجمع مطاعم عالمية وفعاليات موسمية ومساحات خضراء. من أكثر الوجهات حيوية في العاصمة على مدار العام.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.7701,
      lng: 46.6012,
      address: 'حي الصحافة، الرياض',
      img1: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
      rate: 4.8,
      sortOrder: 3,
      daysAgo: 300,
      isPartner: true,
      phone: '+966115551234',
    ),
    ProductionSeedLandmark(
      id: 'mkan_national_museum',
      name: 'المتحف الوطني السعودي',
      description:
          'يعرض مسيرة الجزيرة العربية من عصور ما قبل التاريخ حتى الدولة الحديثة. مناسب للزيارات العائلية والبرامج التعليمية.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.6472,
      lng: 46.7091,
      address: 'طريق الملك فيصل، الرياض',
      img1: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
      rate: 4.6,
      sortOrder: 4,
      daysAgo: 280,
    ),
    ProductionSeedLandmark(
      id: 'mkan_wadi_hanifa',
      name: 'وادي حنيفة',
      description:
          'متنفس طبيعي داخل الرياض مع مسارات مشي وركوب دراجات ومناطق جلوس. وجهة مفضلة في الشتاء والعصر.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.6469,
      lng: 46.6093,
      address: 'وادي حنيفة، الرياض',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.5,
      sortOrder: 5,
      daysAgo: 260,
    ),
    ProductionSeedLandmark(
      id: 'mkan_clock_tower',
      name: 'أبراج الساعة — مكة',
      description:
          'مجمع ضخم قرب الحرم يضم فنادق فاخرة ومراكز تسوق. نقطة انطلاق مثالية لزوار مكة المكرمة.',
      regionId: 'region_makkah',
      cityId: 'city_makkah',
      lat: 21.4189,
      lng: 39.8257,
      address: 'أبراج البيت، مكة المكرمة',
      img1: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f1fa?w=1200&q=80',
      isMosque: true,
      rate: 4.8,
      sortOrder: 6,
      daysAgo: 350,
      isPartner: true,
      phone: '+966125555000',
    ),
    ProductionSeedLandmark(
      id: 'mkan_jeddah_corniche',
      name: 'كورنيش جدة — نافورة الملك فهد',
      description:
          'أطول نافورة مائية في العالم مع كورنيش ممتد للمشي والمقاهي. من أشهر معالم جدة ليلاً ونهاراً.',
      regionId: 'region_makkah',
      cityId: 'city_jeddah',
      lat: 21.5169,
      lng: 39.1748,
      address: 'كورنيش جدة',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.7,
      sortOrder: 7,
      daysAgo: 310,
    ),
    ProductionSeedLandmark(
      id: 'mkan_albalad',
      name: 'جدة التاريخية — البلد',
      description:
          'حي تراثي مسجل في اليونسكو بأزقة تراثية وبيوت حجازية ومطاعم شعبية. يعكس هوية جدة البحرية العريقة.',
      regionId: 'region_makkah',
      cityId: 'city_jeddah',
      lat: 21.4815,
      lng: 39.1862,
      address: 'البلد، جدة',
      img1: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      rate: 4.8,
      sortOrder: 8,
      daysAgo: 290,
    ),
    ProductionSeedLandmark(
      id: 'mkan_taif_roses',
      name: 'مزارع الورود — الطائف',
      description:
          'تجربة موسم الورود في مصيف المملكة مع جولات مزارع ومنتجات عطرية. مثالية في الربيع والصيف.',
      regionId: 'region_makkah',
      cityId: 'city_taif',
      lat: 21.2703,
      lng: 40.4158,
      address: 'الشفا، الطائف',
      img1: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1200&q=80',
      rate: 4.6,
      sortOrder: 9,
      daysAgo: 200,
    ),
    ProductionSeedLandmark(
      id: 'mkan_quba',
      name: 'مسجد قباء',
      description:
          'أول مسجد بني في الإسلام في المدينة المنورة. يزوره الحجاج والمعتمرون ضمن برامج الزيارة الدينية.',
      regionId: 'region_madinah',
      cityId: 'city_madinah',
      lat: 24.4392,
      lng: 39.6172,
      address: 'مسجد قباء، المدينة المنورة',
      img1: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f1fa?w=1200&q=80',
      isMosque: true,
      rate: 4.9,
      sortOrder: 10,
      daysAgo: 330,
    ),
    ProductionSeedLandmark(
      id: 'mkan_uhud',
      name: 'جبل أحد',
      description:
          'موقع تاريخي وديني مهم مع مسارات زيارة وإطلالات على المدينة. يُنصح بزيارته في الصباح الباكر.',
      regionId: 'region_madinah',
      cityId: 'city_madinah',
      lat: 24.5015,
      lng: 39.6163,
      address: 'جبل أحد، المدينة المنورة',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      isMosque: true,
      rate: 4.8,
      sortOrder: 11,
      daysAgo: 270,
    ),
    ProductionSeedLandmark(
      id: 'mkan_hegra',
      name: 'مدائن صالح — الحِجر',
      description:
          'أول موقع سعودي في قائمة اليونسكو بنقوش نبطية وقبور منحوتة في الصخور. جوهرة العلا السياحية.',
      regionId: 'region_alula',
      cityId: 'city_alula',
      lat: 26.7919,
      lng: 37.9525,
      address: 'الحِجر، العلا',
      img1: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
      img2: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.9,
      sortOrder: 12,
      daysAgo: 360,
      isPartner: true,
      phone: '+966148200000',
    ),
    ProductionSeedLandmark(
      id: 'mkan_old_town_alula',
      name: 'البلدة القديمة — العلا',
      description:
          'متاهة من الطين والحجر مع مقاهي تراثية ومعارض فنية. تجربة ثقافية فريدة في شمال المملكة.',
      regionId: 'region_alula',
      cityId: 'city_alula',
      lat: 26.6142,
      lng: 37.9250,
      address: 'البلدة القديمة، العلا',
      img1: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
      rate: 4.7,
      sortOrder: 13,
      daysAgo: 240,
    ),
    ProductionSeedLandmark(
      id: 'mkan_dammam_corniche',
      name: 'كورنيش الدمام',
      description:
          'واجهة بحرية على الخليج العربي مع ممشى وحدائق ومرافق عائلية. وجهة نهاية الأسبوع في الشرقية.',
      regionId: 'region_eastern',
      cityId: 'city_dammam',
      lat: 26.4834,
      lng: 50.1121,
      address: 'كورنيش الدمام',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.5,
      sortOrder: 14,
      daysAgo: 220,
    ),
    ProductionSeedLandmark(
      id: 'mkan_marjan_island',
      name: 'جزيرة المرجان — الخبر',
      description:
          'جزيرة اصطناعية للتسوق والمطاعم مع إطلالة بحرية. من أبرز معالم الواجهة البحرية في المنطقة الشرقية.',
      regionId: 'region_eastern',
      cityId: 'city_alkhobar',
      lat: 26.2172,
      lng: 50.1971,
      address: 'جزيرة المرجان، الخبر',
      img1: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      rate: 4.6,
      sortOrder: 15,
      daysAgo: 190,
    ),
    ProductionSeedLandmark(
      id: 'mkan_rijal_almaa',
      name: 'قرية رجال ألمع',
      description:
          'قرية تراثية جبلية بعمارة حجرية مميزة. من أجمل القرى التراثية في عسير وتصلح للتصوير والسياحة الثقافية.',
      regionId: 'region_asir',
      cityId: 'city_rijal',
      lat: 18.2125,
      lng: 42.4167,
      address: 'رجال ألمع، عسير',
      img1: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
      rate: 4.8,
      sortOrder: 16,
      daysAgo: 250,
      isPartner: true,
      phone: '+966172222333',
    ),
    ProductionSeedLandmark(
      id: 'mkan_habala',
      name: 'حبلة الربع',
      description:
          'قرية معلقة على منحدر جبلي كانت تُوصل بالحبال. تجربة سياحية مميزة في جبال عسير مع تلفريك.',
      regionId: 'region_asir',
      cityId: 'city_abha',
      lat: 18.0350,
      lng: 42.9250,
      address: 'حبلة الربع، أبها',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.7,
      sortOrder: 17,
      daysAgo: 210,
    ),
    ProductionSeedLandmark(
      id: 'mkan_abha_resort',
      name: 'منتجع أبها السياحي',
      description:
          'منتجع جبلي بإطلالات ضبابية ومسارات طبيعية. مثالي للهروب من حر الصيف في مرتفعات عسير.',
      regionId: 'region_asir',
      cityId: 'city_abha',
      lat: 18.2164,
      lng: 42.5053,
      address: 'أبها، عسير',
      img1: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      rate: 4.6,
      sortOrder: 18,
      daysAgo: 170,
    ),
    ProductionSeedLandmark(
      id: 'mkan_wadi_disah',
      name: 'وادي الديسة',
      description:
          'وادي أخضر محاط بجبال شاهقة في تبوك. من أجمل الوجهات الطبيعية للتخييم والمشي والتصوير.',
      regionId: 'region_tabuk',
      cityId: 'city_tabuk',
      lat: 28.3667,
      lng: 36.5833,
      address: 'وادي الديسة، تبوك',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.9,
      sortOrder: 19,
      daysAgo: 230,
    ),
    ProductionSeedLandmark(
      id: 'mkan_hail_fort',
      name: 'قلعة عرفة — حائل',
      description:
          'قلعة تاريخية في قلب حائل تعكس عمارة نجد. موقع ثقافي يستقطب محبي التاريخ والتراث.',
      regionId: 'region_hail',
      cityId: 'city_hail',
      lat: 27.5114,
      lng: 41.6900,
      address: 'قلعة عرفة، حائل',
      img1: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
      rate: 4.5,
      sortOrder: 20,
      daysAgo: 150,
    ),
    ProductionSeedLandmark(
      id: 'mkan_king_abdullah_park',
      name: 'منتزه الملك عبدالله — الرياض',
      description:
          'أحد أكبر الحدائق الحضرية في العالم بمساحات خضراء ونافورة راقصة ومناطق لعب. وجهة عائلية مثالية في عطلة نهاية الأسبوع.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.6668,
      lng: 46.7382,
      address: 'طريق الإمام سعود بن فيصل، الرياض',
      img1: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1200&q=80',
      rate: 4.7,
      sortOrder: 21,
      daysAgo: 145,
    ),
    ProductionSeedLandmark(
      id: 'mkan_diplomatic_quarter',
      name: 'حي السفارات — واجهة الرياض',
      description:
          'منطقة حديثة بتصميم معماري فريد وممرات مشاة ومعارض فنية ومقاهي راقية. من أبرز مشاريع تطوير العاصمة.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.6908,
      lng: 46.6197,
      address: 'حي السفارات، الرياض',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.6,
      sortOrder: 22,
      daysAgo: 130,
    ),
    ProductionSeedLandmark(
      id: 'mkan_imam_saudi_reserve',
      name: 'محمية الملك عبدالعزيز الملكية',
      description:
          'محمية طبيعية شمال الرياض تضم غزلان وظباء ونباتات برية. تقدم جولات بيئية وسياحة بصحراء نجد.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 25.2083,
      lng: 46.6083,
      address: 'محمية الإمام عبدالعزيز، الرياض',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      isFood: false,
      rate: 4.5,
      sortOrder: 23,
      daysAgo: 115,
      category: 'طبيعة ومغامرات',
    ),
    ProductionSeedLandmark(
      id: 'mkan_jabal_nour',
      name: 'غار حراء — جبل النور',
      description:
          'موقع تاريخي في مكة يزوره الحجاج والمعتمرون. يقع على ارتفاع ويتطلب مشياً معتدلاً مع إطلالة على المدينة.',
      regionId: 'region_makkah',
      cityId: 'city_makkah',
      lat: 21.4575,
      lng: 39.8592,
      address: 'جبل النور، مكة المكرمة',
      img1: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f1fa?w=1200&q=80',
      isMosque: true,
      rate: 4.9,
      sortOrder: 24,
      daysAgo: 335,
      category: 'مواقع دينية',
    ),
    ProductionSeedLandmark(
      id: 'mkan_okaz_market',
      name: 'سوق عكاظ التراثي — الطائف',
      description:
          'سوق تراثي يعيد إحياء أسواق العرب القديمة مع عروض شعرية وحرف يدوية ومأكولات شعبية. يقام في موسم الصيف.',
      regionId: 'region_makkah',
      cityId: 'city_taif',
      lat: 21.3549,
      lng: 40.4167,
      address: 'سوق عكاظ، الطائف',
      img1: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
      rate: 4.7,
      sortOrder: 25,
      daysAgo: 185,
      category: 'تراث وثقافة',
    ),
    ProductionSeedLandmark(
      id: 'mkan_taif_cable_car',
      name: 'تلفريك الهدا — الطائف',
      description:
          'تجربة تلفريك فوق جبال الهدا بإطلالات بانورامية وحدائق ومنتجعات. من أشهر أنشطة المصيف في المملكة.',
      regionId: 'region_makkah',
      cityId: 'city_taif',
      lat: 21.0686,
      lng: 40.2886,
      address: 'الهدا، الطائف',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.8,
      sortOrder: 26,
      daysAgo: 165,
      isPartner: true,
      phone: '+966127500000',
    ),
    ProductionSeedLandmark(
      id: 'mkan_quba_walk',
      name: 'مسجد القبلتين',
      description:
          'مسجد تاريخي في المدينة يتميز بقبلة مزدوجة في تاريخه الإسلامي. يقع في مسار زيارات المعالم الدينية.',
      regionId: 'region_madinah',
      cityId: 'city_madinah',
      lat: 24.4842,
      lng: 39.5792,
      address: 'مسجد القبلتين، المدينة المنورة',
      img1: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f1fa?w=1200&q=80',
      isMosque: true,
      rate: 4.8,
      sortOrder: 27,
      daysAgo: 255,
      category: 'مواقع دينية',
    ),
    ProductionSeedLandmark(
      id: 'mkan_elephant_rock',
      name: 'صخرة الفيل — العلا',
      description:
          'تكوين صخري طبيعي ضخم على شكل فيل يضيء ليلاً بعروض ضوئية. من أكثر المواقع تصويراً في العلا.',
      regionId: 'region_alula',
      cityId: 'city_alula',
      lat: 26.6164,
      lng: 37.9503,
      address: 'صخرة الفيل، العلا',
      img1: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
      img2: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.9,
      sortOrder: 28,
      daysAgo: 225,
      isPartner: true,
      phone: '+966148201111',
    ),
    ProductionSeedLandmark(
      id: 'mkan_maraya_alula',
      name: 'مرايا — قاعة العلا',
      description:
          'قاعة فعاليات عالمية بواجهة مرآة عاكسة تعكس صحراء العلا. تستضيف حفلات ومؤتمرات وفعاليات ثقافية.',
      regionId: 'region_alula',
      cityId: 'city_alula',
      lat: 26.6149,
      lng: 37.9230,
      address: 'مرايا، العلا',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.8,
      sortOrder: 29,
      daysAgo: 205,
      category: 'معالم حديثة',
    ),
    ProductionSeedLandmark(
      id: 'mkan_half_moon_beach',
      name: 'شاطئ نصف القمر — الخبر',
      description:
          'شاطئ رملي أبيض على ساحل الخليج مع منتجعات ومطاعم بحرية. من أشهر شواطئ المنطقة الشرقية.',
      regionId: 'region_eastern',
      cityId: 'city_alkhobar',
      lat: 26.2010,
      lng: 50.1975,
      address: 'شاطئ نصف القمر، الخبر',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.7,
      sortOrder: 30,
      daysAgo: 175,
    ),
    ProductionSeedLandmark(
      id: 'mkan_king_fahd_park_dammam',
      name: 'منتزه الملك فهد — الدمام',
      description:
          'حديقة واسعة في الدمام ببحيرة صناعية ومسارات مشي ومناطق شواء. مفضلة للعائلات في المساء.',
      regionId: 'region_eastern',
      cityId: 'city_dammam',
      lat: 26.4360,
      lng: 50.1030,
      address: 'منتزه الملك فهد، الدمام',
      img1: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1200&q=80',
      rate: 4.5,
      sortOrder: 31,
      daysAgo: 160,
    ),
    ProductionSeedLandmark(
      id: 'mkan_alahsa_oasis',
      name: 'واحة الأحساء',
      description:
          'أكبر واحة نخيل في العالم مسجلة في اليونسكو. تضم مزارع نخيل وقصور تراثية وأسواقاً محلية.',
      regionId: 'region_ahsa',
      cityId: 'city_hofuf',
      lat: 25.3832,
      lng: 49.5877,
      address: 'واحة الأحساء، الهفوف',
      img1: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      rate: 4.8,
      sortOrder: 32,
      daysAgo: 195,
      category: 'تراث وثقافة',
      isPartner: true,
      phone: '+966138888000',
    ),
    ProductionSeedLandmark(
      id: 'mkan_qara_mountain',
      name: 'جبل القارة — الأحساء',
      description:
          'جبل جيري بكهوف طبيعية وإطلالة على الواحة. يوفر مسارات مشي قصيرة وتجربة طبيعية فريدة في الشرقية.',
      regionId: 'region_ahsa',
      cityId: 'city_hofuf',
      lat: 25.4210,
      lng: 49.6700,
      address: 'جبل القارة، الهفوف',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.6,
      sortOrder: 33,
      daysAgo: 140,
      category: 'طبيعة ومغامرات',
    ),
    ProductionSeedLandmark(
      id: 'mkan_soudah',
      name: 'منتزه السودة — أبها',
      description:
          'أعلى قمة في المملكة بغطاء ضبابي وغابات عرعر. تلفريك ومطاعم وإطلالات خلابة على سحب عسير.',
      regionId: 'region_asir',
      cityId: 'city_abha',
      lat: 18.2667,
      lng: 42.3667,
      address: 'السودة، أبها',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      img2: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1200&q=80',
      rate: 4.9,
      sortOrder: 34,
      daysAgo: 155,
    ),
    ProductionSeedLandmark(
      id: 'mkan_green_mountain',
      name: 'الجبل الأخضر — أبها',
      description:
          'تلة خضراء مطلة على مدينة أبها مع مقاهي ومطاعم وإضاءة ليلية. من أبرز معالم المدينة السياحية.',
      regionId: 'region_asir',
      cityId: 'city_abha',
      lat: 18.2300,
      lng: 42.5100,
      address: 'الجبل الأخضر، أبها',
      img1: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
      rate: 4.7,
      sortOrder: 35,
      daysAgo: 125,
    ),
    ProductionSeedLandmark(
      id: 'mkan_jabal_allawz',
      name: 'جبل اللوز — تبوك',
      description:
          'جبال وردية/حمراء فريدة في صحراء تبوك. وجهة تصوير ومغامرات شهيرة خاصة عند الغروب.',
      regionId: 'region_tabuk',
      cityId: 'city_tabuk',
      lat: 28.6550,
      lng: 35.6900,
      address: 'جبل اللوز، تبوك',
      img1: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
      rate: 4.8,
      sortOrder: 36,
      daysAgo: 215,
      category: 'طبيعة ومغامرات',
    ),
    ProductionSeedLandmark(
      id: 'mkan_haql_shipwreck',
      name: 'شاطئ حقل — سفينة جورجيوس',
      description:
          'شواطئ فيروزية في أقصى الشمال مع حطام سفينة تاريخية. مثالية للغوص والتخييم والتصوير.',
      regionId: 'region_tabuk',
      cityId: 'city_tabuk',
      lat: 29.2847,
      lng: 34.7814,
      address: 'شاطئ حقل، تبوك',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.7,
      sortOrder: 37,
      daysAgo: 180,
    ),
    ProductionSeedLandmark(
      id: 'mkan_jabal_aja',
      name: 'جبل أجا — حائل',
      description:
          'تكوينات صخرية شاهقة قرب حائل مع نقوش ثمودية ومسارات مشي. من أجمل معالم الطبيعة في شمال المملكة.',
      regionId: 'region_hail',
      cityId: 'city_hail',
      lat: 27.5000,
      lng: 41.7500,
      address: 'جبل أجا، حائل',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.6,
      sortOrder: 38,
      daysAgo: 135,
      category: 'طبيعة ومغامرات',
    ),
    ProductionSeedLandmark(
      id: 'mkan_farsan_islands',
      name: 'جزر فرسان',
      description:
          'أرخبيل في البحر الأحمر بشعاب مرجانية وغزلان بحرية وشواطئ بكر. وجهة غوص وسياحة بحرية متميزة.',
      regionId: 'region_jazan',
      cityId: 'city_farsan',
      lat: 16.7022,
      lng: 42.1183,
      address: 'جزر فرسان، جازان',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.9,
      sortOrder: 39,
      daysAgo: 245,
      isPartner: true,
      phone: '+966173333444',
    ),
    ProductionSeedLandmark(
      id: 'mkan_farasan_marine',
      name: 'المحمية البحرية — فرسان',
      description:
          'محمية بيئية تحتضن أنواعاً نادرة من الطيور البحرية والسلاحف. جولات قوارب ومرشدون محليون.',
      regionId: 'region_jazan',
      cityId: 'city_farsan',
      lat: 16.8230,
      lng: 42.0500,
      address: 'محمية فرسان، جازان',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.7,
      sortOrder: 40,
      daysAgo: 120,
      category: 'طبيعة ومغامرات',
    ),
    ProductionSeedLandmark(
      id: 'mkan_najran_heritage',
      name: 'قرية الحجر — نجران',
      description:
          'موقع أثري بنمط معماري يمني-جنوبي فريد في الجزيرة العربية. يضم قلاعاً طينية وأسواقاً تراثية.',
      regionId: 'region_najran',
      cityId: 'city_najran',
      lat: 17.4925,
      lng: 44.1278,
      address: 'الحجر، نجران',
      img1: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
      rate: 4.8,
      sortOrder: 41,
      daysAgo: 235,
      category: 'تراث وثقافة',
    ),
    ProductionSeedLandmark(
      id: 'mkan_ukhdud_najran',
      name: 'أخدود نجران',
      description:
          'موقع تاريخي وديني مذكور في القرآن الكريم. يضم متحفاً مفتوحاً ونقوشاً أثرية وتجربة ثقافية عميقة.',
      regionId: 'region_najran',
      cityId: 'city_najran',
      lat: 17.5450,
      lng: 44.2150,
      address: 'أخدود نجران',
      img1: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
      isMosque: true,
      rate: 4.7,
      sortOrder: 42,
      daysAgo: 210,
      category: 'مواقع دينية',
    ),
    ProductionSeedLandmark(
      id: 'mkan_qassim_palm',
      name: 'مزارع النخيل — بريدة',
      description:
          'سهول نخيل واسعة في القصيم مع مهرجانات تمور ومزارع عائلية. تعكس هوية الزراعة في نجد.',
      regionId: 'region_qassim',
      cityId: 'city_buraidah',
      lat: 26.3260,
      lng: 43.9750,
      address: 'بريدة، القصيم',
      img1: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      rate: 4.5,
      sortOrder: 43,
      daysAgo: 100,
      category: 'تراث وثقافة',
    ),
    ProductionSeedLandmark(
      id: 'mkan_unaizah_market',
      name: 'سوق السبت — عنيزة',
      description:
          'سوق شعبي تاريخي في عنيزة للمستعمل والتحف والمأكولات. يعكس حياة نجد الاجتماعية الأصيلة.',
      regionId: 'region_qassim',
      cityId: 'city_unaizah',
      lat: 26.0833,
      lng: 43.9833,
      address: 'سوق السبت، عنيزة',
      img1: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
      rate: 4.4,
      sortOrder: 44,
      daysAgo: 90,
      category: 'تراث وثقافة',
    ),
    ProductionSeedLandmark(
      id: 'mkan_neom_bay',
      name: 'خليج نيوم — شاطئ البحر الأحمر',
      description:
          'وجهة ساحلية حديثة ضمن مشروع نيوم بمياه فيروزية وشعاب مرجانية. تقدم أنشطة بحرية ومنتجعات فاخرة.',
      regionId: 'region_tabuk',
      cityId: 'city_tabuk',
      lat: 28.1000,
      lng: 35.3000,
      address: 'نيوم، تبوك',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      img2: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      rate: 4.8,
      sortOrder: 45,
      daysAgo: 60,
      isPartner: true,
      phone: '+966144000000',
      category: 'معالم حديثة',
    ),
    ProductionSeedLandmark(
      id: 'mkan_riyadh_front',
      name: 'واجهة الرياض — المشروع الملكي',
      description:
          'مشروع ضخم على ضفة وادي حنيفة يضم فنادق ومطاعم ومساحات فعاليات. يمثل مستقبل الترفيه في العاصمة.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.7400,
      lng: 46.5900,
      address: 'واجهة الرياض',
      img1: 'https://images.unsplash.com/photo-1586728122893-0b47a745f769?w=1200&q=80',
      rate: 4.7,
      sortOrder: 46,
      daysAgo: 45,
      category: 'معالم حديثة',
    ),
    ProductionSeedLandmark(
      id: 'mkan_jazan_corniche',
      name: 'كورنيش جازان',
      description:
          'واجهة بحرية على البحر الأحمر مع مطاعم وممشى وإطلالة على جبال فيفاء. من أجمل كورنيشات الجنوب.',
      regionId: 'region_jazan',
      cityId: 'city_jazan',
      lat: 16.8894,
      lng: 42.5611,
      address: 'كورنيش جازان',
      img1: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
      rate: 4.6,
      sortOrder: 47,
      daysAgo: 110,
    ),
    ProductionSeedLandmark(
      id: 'mkan_fifa_mountains',
      name: 'جبال فيفاء — جازان',
      description:
          'جبال خضراء وقرى معلقة ومصاطب زراعية فريدة. تُعرف بـ "سويسرا العرب" لجمالها الطبيعي.',
      regionId: 'region_jazan',
      cityId: 'city_jazan',
      lat: 17.2500,
      lng: 43.1000,
      address: 'فيفاء، جازان',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.9,
      sortOrder: 48,
      daysAgo: 200,
      category: 'طبيعة ومغامرات',
    ),
    ProductionSeedLandmark(
      id: 'mkan_masmak_fort',
      name: 'قصر المصمك التاريخي',
      description:
          'قلعة طينية في قلب الرياض شهدت أحداث توحيد المملكة. يضم متحفاً ومعروضات تاريخية تفاعلية.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.6312,
      lng: 46.7134,
      address: 'حي الديرة، الرياض',
      img1: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
      rate: 4.8,
      sortOrder: 49,
      daysAgo: 300,
      category: 'تراث وثقافة',
    ),
    ProductionSeedLandmark(
      id: 'mkan_edge_world',
      name: 'حافة العالم — الرياض',
      description:
          'جرف صخري مرتفع مطل على سهل تار قرب الرياض. من أشهر وجهات التخييم ومشاهدة الغروب في نجد.',
      regionId: 'region_riyadh',
      cityId: 'city_riyadh',
      lat: 24.9010,
      lng: 46.4020,
      address: 'حافة العالم، الرياض',
      img1: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      rate: 4.9,
      sortOrder: 50,
      daysAgo: 80,
      category: 'طبيعة ومغامرات',
      isPartner: true,
      phone: '+966115566777',
    ),
  ];
}
