const fs = require("fs");
const path = require("path");

const values = {
  en: {
    card_invalid_data: "Card details are invalid",
    card_number_label: "Card number",
    dialog_continue: "Continue",
    map_load_failed: "The map could not load. Check your connection and map service settings.",
    payment_failed_message: "Payment was not completed. Check your card and try again.",
    payment_order_save_error: "The order could not be saved. Contact support if you were charged.",
    payment_pending_message: "Payment is still pending. Please wait or try again.",
    payment_verify_error: "Payment could not be verified. Please try again.",
    ux_card_payment_network: "Secure card payment via Network International",
    ux_change: "Change",
    wallet_amount_exceeds_balance: "Amount exceeds available balance",
    wallet_card_topup_success: "Wallet topped up successfully. Return to wallet?",
    wallet_choose_payout: "Choose the card to receive funds:",
    wallet_withdraw_confirm: "Withdraw",
    wallet_withdraw_description: "Withdraw from wallet",
    wallet_withdraw_no_card_deposit: "No card deposit covers this withdrawal amount",
    wallet_withdraw_refund_failed: "Payment refund failed",
    wallet_withdraw_success: "Withdrew {amount} {currency} successfully",
    map_trip_destination: "Trip destination",
    map_invalid_destinations: "{count} invalid or out-of-area stop(s) were excluded from the route.",
    checkout_estimated_time_warning: "The estimated drive time ({time}) is shorter than the recommended booking duration. Traffic may affect the estimate.",
    checkout_vat_rate: "VAT ({rate}%):",
    map_location_unavailable: "Your current location is unavailable.",
    map_no_valid_destinations: "No valid stops are available for this route.",
    unit_km: "km", unit_meter: "m", unit_minute: "min", unit_hour: "h", unit_kmh: "km/h",
    duration_hours_minutes: "{hours} h {minutes} min",
    location_city_unresolved: "Your city could not be determined accurately."
  },
  ar: {
    card_invalid_data: "بيانات البطاقة غير صحيحة",
    card_number_label: "رقم البطاقة",
    dialog_continue: "متابعة",
    map_load_failed: "تعذر تحميل الخريطة. تحقق من الاتصال وإعدادات خدمة الخرائط.",
    payment_failed_message: "لم تكتمل عملية الدفع. تحقق من البطاقة وحاول مرة أخرى.",
    payment_order_save_error: "تعذر حفظ الطلب. تواصل مع الدعم إذا تم خصم المبلغ.",
    payment_pending_message: "عملية الدفع ما زالت قيد المعالجة. انتظر قليلاً أو حاول مرة أخرى.",
    payment_verify_error: "تعذر التحقق من عملية الدفع. حاول مرة أخرى.",
    ux_card_payment_network: "دفع آمن بالبطاقة عبر Network International",
    ux_change: "تغيير",
    wallet_amount_exceeds_balance: "المبلغ يتجاوز الرصيد المتاح",
    wallet_card_topup_success: "تم شحن المحفظة بنجاح. هل تريد العودة إلى المحفظة؟",
    wallet_choose_payout: "اختر البطاقة التي ستستقبل المبلغ:",
    wallet_withdraw_confirm: "سحب",
    wallet_withdraw_description: "سحب من المحفظة",
    wallet_withdraw_no_card_deposit: "لا توجد عملية إيداع بالبطاقة تغطي مبلغ السحب",
    wallet_withdraw_refund_failed: "تعذر استرداد مبلغ الدفع",
    wallet_withdraw_success: "تم سحب {amount} {currency} بنجاح",
    map_trip_destination: "وجهة الرحلة",
    map_invalid_destinations: "تم استبعاد {count} محطة غير صالحة أو خارج النطاق من المسار.",
    checkout_estimated_time_warning: "وقت القيادة التقديري ({time}) أقصر من مدة الحجز الموصى بها، وقد تؤثر حركة المرور في التقدير.",
    checkout_vat_rate: "ضريبة القيمة المضافة ({rate}%):",
    map_location_unavailable: "تعذر الحصول على موقعك الحالي.",
    map_no_valid_destinations: "لا توجد محطات صالحة لحساب هذا المسار.",
    unit_km: "كم", unit_meter: "م", unit_minute: "دقيقة", unit_hour: "ساعة", unit_kmh: "كم/س",
    duration_hours_minutes: "{hours} ساعة و{minutes} دقيقة",
    location_city_unresolved: "تعذر تحديد مدينتك بدقة."
  },
  ru: {
    card_invalid_data: "Данные карты недействительны",
    card_number_label: "Номер карты",
    dialog_continue: "Продолжить",
    map_load_failed: "Не удалось загрузить карту. Проверьте подключение и настройки карт.",
    payment_failed_message: "Платёж не завершён. Проверьте карту и повторите попытку.",
    payment_order_save_error: "Не удалось сохранить заказ. Если деньги списаны, обратитесь в поддержку.",
    payment_pending_message: "Платёж ещё обрабатывается. Подождите или повторите попытку.",
    payment_verify_error: "Не удалось проверить платёж. Повторите попытку.",
    ux_card_payment_network: "Безопасная оплата картой через Network International",
    ux_change: "Изменить",
    wallet_amount_exceeds_balance: "Сумма превышает доступный баланс",
    wallet_card_topup_success: "Кошелёк пополнен. Вернуться в кошелёк?",
    wallet_choose_payout: "Выберите карту для получения средств:",
    wallet_withdraw_confirm: "Вывести",
    wallet_withdraw_description: "Вывод средств из кошелька",
    wallet_withdraw_no_card_deposit: "Нет пополнения с карты, покрывающего сумму вывода",
    wallet_withdraw_refund_failed: "Не удалось вернуть платёж",
    wallet_withdraw_success: "Успешно выведено {amount} {currency}",
    map_trip_destination: "Пункт назначения",
    map_invalid_destinations: "Из маршрута исключено недопустимых или удалённых остановок: {count}.",
    checkout_estimated_time_warning: "Расчётное время в пути ({time}) меньше рекомендуемой длительности бронирования. На расчёт может повлиять дорожная обстановка.",
    checkout_vat_rate: "НДС ({rate}%):",
    map_location_unavailable: "Текущее местоположение недоступно.",
    map_no_valid_destinations: "Для этого маршрута нет допустимых остановок.",
    unit_km: "км", unit_meter: "м", unit_minute: "мин", unit_hour: "ч", unit_kmh: "км/ч",
    duration_hours_minutes: "{hours} ч {minutes} мин",
    location_city_unresolved: "Не удалось точно определить ваш город."
  },
  ky: {
    card_invalid_data: "Карта маалыматы жараксыз",
    card_number_label: "Карта номери",
    dialog_continue: "Улантуу",
    map_load_failed: "Карта жүктөлгөн жок. Интернет байланышын жана карта кызматынын жөндөөлөрүн текшериңиз.",
    payment_failed_message: "Төлөм аяктаган жок. Картаны текшерип, кайра аракет кылыңыз.",
    payment_order_save_error: "Буйрутманы сактоо мүмкүн болгон жок. Акча алынган болсо, колдоо кызматына кайрылыңыз.",
    payment_pending_message: "Төлөм дагы иштетилүүдө. Бир аз күтүңүз же кайра аракет кылыңыз.",
    payment_verify_error: "Төлөмдү текшерүү мүмкүн болгон жок. Кайра аракет кылыңыз.",
    ux_card_payment_network: "Network International аркылуу коопсуз карта төлөмү",
    ux_change: "Өзгөртүү",
    wallet_amount_exceeds_balance: "Сумма жеткиликтүү баланстан ашат",
    wallet_card_topup_success: "Капчык ийгиликтүү толукталды. Капчыкка кайтасызбы?",
    wallet_choose_payout: "Каражат түшө турган картаны тандаңыз:",
    wallet_withdraw_confirm: "Чыгарып алуу",
    wallet_withdraw_description: "Капчыктан каражат чыгаруу",
    wallet_withdraw_no_card_deposit: "Бул сумманы жаба турган карта аркылуу толуктоо жок",
    wallet_withdraw_refund_failed: "Төлөмдү кайтаруу мүмкүн болгон жок",
    wallet_withdraw_success: "{amount} {currency} ийгиликтүү чыгарылды",
    map_trip_destination: "Сапардын көздөгөн жери",
    map_invalid_destinations: "Маршруттан жараксыз же аймактан тышкаркы {count} аялдама чыгарылды.",
    checkout_estimated_time_warning: "Болжолдуу жол убактысы ({time}) сунушталган брондоо мөөнөтүнөн кыска. Жол кыймылы эсепке таасир этиши мүмкүн.",
    checkout_vat_rate: "КНС ({rate}%):",
    map_location_unavailable: "Учурдагы жайгашкан жериңиз жеткиликсиз.",
    map_no_valid_destinations: "Бул маршрут үчүн жарактуу аялдамалар жок.",
    unit_km: "км", unit_meter: "м", unit_minute: "мүн", unit_hour: "саат", unit_kmh: "км/саат",
    duration_hours_minutes: "{hours} саат {minutes} мүнөт",
    location_city_unresolved: "Шаарыңызды так аныктоо мүмкүн болгон жок."
  },
  az: {
    card_invalid_data: "Kart məlumatları yanlışdır",
    card_number_label: "Kart nömrəsi",
    dialog_continue: "Davam et",
    map_load_failed: "Xəritə yüklənmədi. İnternet bağlantısını və xəritə xidməti ayarlarını yoxlayın.",
    payment_failed_message: "Ödəniş tamamlanmadı. Kartı yoxlayın və yenidən cəhd edin.",
    payment_order_save_error: "Sifariş saxlanmadı. Məbləğ tutulubsa, dəstək xidməti ilə əlaqə saxlayın.",
    payment_pending_message: "Ödəniş hələ işlənir. Gözləyin və ya yenidən cəhd edin.",
    payment_verify_error: "Ödənişi təsdiqləmək mümkün olmadı. Yenidən cəhd edin.",
    ux_card_payment_network: "Network International vasitəsilə təhlükəsiz kart ödənişi",
    ux_change: "Dəyişdir",
    wallet_amount_exceeds_balance: "Məbləğ mövcud balansı aşır",
    wallet_card_topup_success: "Pul kisəsi uğurla artırıldı. Pul kisəsinə qayıdılsın?",
    wallet_choose_payout: "Vəsaiti qəbul edəcək kartı seçin:",
    wallet_withdraw_confirm: "Çıxar",
    wallet_withdraw_description: "Pul kisəsindən vəsait çıxar",
    wallet_withdraw_no_card_deposit: "Çıxarış məbləğini qarşılayan kart mədaxili yoxdur",
    wallet_withdraw_refund_failed: "Ödənişi geri qaytarmaq mümkün olmadı",
    wallet_withdraw_success: "{amount} {currency} uğurla çıxarıldı",
    map_trip_destination: "Səfər təyinatı",
    map_invalid_destinations: "Marşrutdan {count} etibarsız və ya ərazidən kənar dayanacaq çıxarıldı.",
    checkout_estimated_time_warning: "Təxmini yol vaxtı ({time}) tövsiyə olunan rezervasiya müddətindən qısadır. Tıxac hesablamaya təsir edə bilər.",
    checkout_vat_rate: "ƏDV ({rate}%):",
    map_location_unavailable: "Cari məkanınız əlçatan deyil.",
    map_no_valid_destinations: "Bu marşrut üçün etibarlı dayanacaq yoxdur.",
    unit_km: "km", unit_meter: "m", unit_minute: "dəq", unit_hour: "saat", unit_kmh: "km/saat",
    duration_hours_minutes: "{hours} saat {minutes} dəqiqə",
    location_city_unresolved: "Şəhərinizi dəqiq müəyyən etmək mümkün olmadı."
  },
  ka: {
    card_invalid_data: "ბარათის მონაცემები არასწორია",
    card_number_label: "ბარათის ნომერი",
    dialog_continue: "გაგრძელება",
    map_load_failed: "რუკა ვერ ჩაიტვირთა. შეამოწმეთ კავშირი და რუკის სერვისის პარამეტრები.",
    payment_failed_message: "გადახდა არ დასრულდა. შეამოწმეთ ბარათი და სცადეთ ხელახლა.",
    payment_order_save_error: "შეკვეთა ვერ შეინახა. თუ თანხა ჩამოგეჭრათ, დაუკავშირდით მხარდაჭერას.",
    payment_pending_message: "გადახდა ჯერ კიდევ მუშავდება. მოიცადეთ ან სცადეთ ხელახლა.",
    payment_verify_error: "გადახდის შემოწმება ვერ მოხერხდა. სცადეთ ხელახლა.",
    ux_card_payment_network: "ბარათით უსაფრთხო გადახდა Network International-ის მეშვეობით",
    ux_change: "შეცვლა",
    wallet_amount_exceeds_balance: "თანხა აღემატება ხელმისაწვდომ ბალანსს",
    wallet_card_topup_success: "საფულე წარმატებით შეივსო. დაბრუნდეთ საფულეში?",
    wallet_choose_payout: "აირჩიეთ თანხის მისაღები ბარათი:",
    wallet_withdraw_confirm: "გატანა",
    wallet_withdraw_description: "თანხის გატანა საფულიდან",
    wallet_withdraw_no_card_deposit: "ამ თანხის გასატანად შესაბამისი ბარათის შეტანა არ არსებობს",
    wallet_withdraw_refund_failed: "გადახდის დაბრუნება ვერ მოხერხდა",
    wallet_withdraw_success: "წარმატებით გაიტანეთ {amount} {currency}",
    map_trip_destination: "მგზავრობის დანიშნულება",
    map_invalid_destinations: "მარშრუტიდან ამოიღეს {count} არასწორი ან ზონის გარეთ მდებარე გაჩერება.",
    checkout_estimated_time_warning: "სავარაუდო მგზავრობის დრო ({time}) რეკომენდებულ ჯავშნის ხანგრძლივობაზე ნაკლებია. მოძრაობამ შეიძლება შეფასებაზე იმოქმედოს.",
    checkout_vat_rate: "დღგ ({rate}%):",
    map_location_unavailable: "თქვენი მიმდინარე მდებარეობა მიუწვდომელია.",
    map_no_valid_destinations: "ამ მარშრუტისთვის სწორი გაჩერებები არ არის.",
    unit_km: "კმ", unit_meter: "მ", unit_minute: "წთ", unit_hour: "სთ", unit_kmh: "კმ/სთ",
    duration_hours_minutes: "{hours} სთ {minutes} წთ",
    location_city_unresolved: "თქვენი ქალაქის ზუსტად განსაზღვრა ვერ მოხერხდა."
  },
  tr: {
    card_invalid_data: "Kart bilgileri geçersiz",
    card_number_label: "Kart numarası",
    dialog_continue: "Devam et",
    map_load_failed: "Harita yüklenemedi. Bağlantınızı ve harita hizmeti ayarlarını kontrol edin.",
    payment_failed_message: "Ödeme tamamlanmadı. Kartınızı kontrol edip tekrar deneyin.",
    payment_order_save_error: "Sipariş kaydedilemedi. Ücret alındıysa destek ekibiyle iletişime geçin.",
    payment_pending_message: "Ödeme hâlâ işleniyor. Lütfen bekleyin veya tekrar deneyin.",
    payment_verify_error: "Ödeme doğrulanamadı. Lütfen tekrar deneyin.",
    ux_card_payment_network: "Network International ile güvenli kart ödemesi",
    ux_change: "Değiştir",
    wallet_amount_exceeds_balance: "Tutar kullanılabilir bakiyeyi aşıyor",
    wallet_card_topup_success: "Cüzdan başarıyla yüklendi. Cüzdana dönülsün mü?",
    wallet_choose_payout: "Paranın aktarılacağı kartı seçin:",
    wallet_withdraw_confirm: "Çek",
    wallet_withdraw_description: "Cüzdandan para çek",
    wallet_withdraw_no_card_deposit: "Çekim tutarını karşılayan bir kart yüklemesi yok",
    wallet_withdraw_refund_failed: "Ödeme iade edilemedi",
    wallet_withdraw_success: "{amount} {currency} başarıyla çekildi",
    map_trip_destination: "Seyahat hedefi",
    map_invalid_destinations: "Geçersiz veya hizmet alanı dışındaki {count} durak rotadan çıkarıldı.",
    checkout_estimated_time_warning: "Tahmini sürüş süresi ({time}), önerilen rezervasyon süresinden kısadır. Trafik tahmini etkileyebilir.",
    checkout_vat_rate: "KDV (%{rate}):",
    map_location_unavailable: "Mevcut konumunuza ulaşılamıyor.",
    map_no_valid_destinations: "Bu rota için geçerli durak bulunamadı.",
    unit_km: "km", unit_meter: "m", unit_minute: "dk", unit_hour: "sa", unit_kmh: "km/sa",
    duration_hours_minutes: "{hours} sa {minutes} dk",
    location_city_unresolved: "Şehriniz kesin olarak belirlenemedi."
  },
  ur: {
    card_invalid_data: "کارڈ کی تفصیلات درست نہیں ہیں",
    card_number_label: "کارڈ نمبر",
    dialog_continue: "جاری رکھیں",
    map_load_failed: "نقشہ لوڈ نہیں ہو سکا۔ انٹرنیٹ اور نقشے کی سروس کی ترتیبات چیک کریں۔",
    payment_failed_message: "ادائیگی مکمل نہیں ہوئی۔ کارڈ چیک کر کے دوبارہ کوشش کریں۔",
    payment_order_save_error: "آرڈر محفوظ نہیں ہو سکا۔ رقم کٹ گئی ہو تو معاونت سے رابطہ کریں۔",
    payment_pending_message: "ادائیگی ابھی زیرِ کارروائی ہے۔ انتظار کریں یا دوبارہ کوشش کریں۔",
    payment_verify_error: "ادائیگی کی تصدیق نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
    ux_card_payment_network: "Network International کے ذریعے محفوظ کارڈ ادائیگی",
    ux_change: "تبدیل کریں",
    wallet_amount_exceeds_balance: "رقم دستیاب بیلنس سے زیادہ ہے",
    wallet_card_topup_success: "والیٹ کامیابی سے بھر گیا۔ والیٹ پر واپس جائیں؟",
    wallet_choose_payout: "رقم وصول کرنے والا کارڈ منتخب کریں:",
    wallet_withdraw_confirm: "رقم نکالیں",
    wallet_withdraw_description: "والیٹ سے رقم نکالیں",
    wallet_withdraw_no_card_deposit: "اس رقم کے لیے کافی کارڈ ڈپازٹ موجود نہیں",
    wallet_withdraw_refund_failed: "ادائیگی واپس نہیں ہو سکی",
    wallet_withdraw_success: "{amount} {currency} کامیابی سے نکالے گئے",
    map_trip_destination: "سفر کی منزل",
    map_invalid_destinations: "{count} غلط یا سروس کے علاقے سے باہر اسٹاپ راستے سے ہٹا دیے گئے۔",
    checkout_estimated_time_warning: "اندازاً سفر کا وقت ({time}) تجویز کردہ بکنگ دورانیے سے کم ہے۔ ٹریفک اس اندازے کو متاثر کر سکتی ہے۔",
    checkout_vat_rate: "ویلیو ایڈڈ ٹیکس ({rate}%):",
    map_location_unavailable: "آپ کا موجودہ مقام دستیاب نہیں ہے۔",
    map_no_valid_destinations: "اس راستے کے لیے کوئی درست اسٹاپ موجود نہیں۔",
    unit_km: "کلومیٹر", unit_meter: "میٹر", unit_minute: "منٹ", unit_hour: "گھنٹہ", unit_kmh: "کلومیٹر/گھنٹہ",
    duration_hours_minutes: "{hours} گھنٹے {minutes} منٹ",
    location_city_unresolved: "آپ کے شہر کا درست تعین نہیں ہو سکا۔"
  },
  fr: {
    card_invalid_data: "Les informations de la carte sont invalides",
    card_number_label: "Numéro de carte",
    dialog_continue: "Continuer",
    map_load_failed: "Impossible de charger la carte. Vérifiez la connexion et les paramètres du service de cartographie.",
    payment_failed_message: "Le paiement n’a pas abouti. Vérifiez la carte et réessayez.",
    payment_order_save_error: "La commande n’a pas pu être enregistrée. Contactez l’assistance si vous avez été débité.",
    payment_pending_message: "Le paiement est toujours en cours. Patientez ou réessayez.",
    payment_verify_error: "Impossible de vérifier le paiement. Réessayez.",
    ux_card_payment_network: "Paiement sécurisé par carte via Network International",
    ux_change: "Modifier",
    wallet_amount_exceeds_balance: "Le montant dépasse le solde disponible",
    wallet_card_topup_success: "Portefeuille rechargé avec succès. Revenir au portefeuille ?",
    wallet_choose_payout: "Choisissez la carte qui recevra les fonds :",
    wallet_withdraw_confirm: "Retirer",
    wallet_withdraw_description: "Retirer des fonds du portefeuille",
    wallet_withdraw_no_card_deposit: "Aucun dépôt par carte ne couvre ce montant de retrait",
    wallet_withdraw_refund_failed: "Le remboursement du paiement a échoué",
    wallet_withdraw_success: "Retrait de {amount} {currency} effectué",
    map_trip_destination: "Destination du trajet",
    map_invalid_destinations: "{count} arrêt(s) invalide(s) ou hors zone ont été exclus de l’itinéraire.",
    checkout_estimated_time_warning: "Le temps de trajet estimé ({time}) est inférieur à la durée de réservation recommandée. La circulation peut modifier cette estimation.",
    checkout_vat_rate: "TVA ({rate} %) :",
    map_location_unavailable: "Votre position actuelle est indisponible.",
    map_no_valid_destinations: "Aucun arrêt valide n’est disponible pour cet itinéraire.",
    unit_km: "km", unit_meter: "m", unit_minute: "min", unit_hour: "h", unit_kmh: "km/h",
    duration_hours_minutes: "{hours} h {minutes} min",
    location_city_unresolved: "Votre ville n’a pas pu être déterminée avec précision."
  },
  id: {
    card_invalid_data: "Detail kartu tidak valid",
    card_number_label: "Nomor kartu",
    dialog_continue: "Lanjutkan",
    map_load_failed: "Peta tidak dapat dimuat. Periksa koneksi dan pengaturan layanan peta.",
    payment_failed_message: "Pembayaran belum selesai. Periksa kartu lalu coba lagi.",
    payment_order_save_error: "Pesanan tidak dapat disimpan. Hubungi dukungan jika saldo telah terpotong.",
    payment_pending_message: "Pembayaran masih diproses. Tunggu atau coba lagi.",
    payment_verify_error: "Pembayaran tidak dapat diverifikasi. Coba lagi.",
    ux_card_payment_network: "Pembayaran kartu aman melalui Network International",
    ux_change: "Ubah",
    wallet_amount_exceeds_balance: "Jumlah melebihi saldo yang tersedia",
    wallet_card_topup_success: "Dompet berhasil diisi. Kembali ke dompet?",
    wallet_choose_payout: "Pilih kartu penerima dana:",
    wallet_withdraw_confirm: "Tarik",
    wallet_withdraw_description: "Tarik dana dari dompet",
    wallet_withdraw_no_card_deposit: "Tidak ada setoran kartu yang mencukupi jumlah penarikan",
    wallet_withdraw_refund_failed: "Pengembalian pembayaran gagal",
    wallet_withdraw_success: "Berhasil menarik {amount} {currency}",
    map_trip_destination: "Tujuan perjalanan",
    map_invalid_destinations: "{count} perhentian yang tidak valid atau di luar area dihapus dari rute.",
    checkout_estimated_time_warning: "Perkiraan waktu berkendara ({time}) lebih singkat daripada durasi pemesanan yang disarankan. Lalu lintas dapat memengaruhi perkiraan.",
    checkout_vat_rate: "PPN ({rate}%):",
    map_location_unavailable: "Lokasi Anda saat ini tidak tersedia.",
    map_no_valid_destinations: "Tidak ada perhentian yang valid untuk rute ini.",
    unit_km: "km", unit_meter: "m", unit_minute: "mnt", unit_hour: "jam", unit_kmh: "km/jam",
    duration_hours_minutes: "{hours} jam {minutes} menit",
    location_city_unresolved: "Kota Anda tidak dapat ditentukan secara akurat."
  },
  "zh-Hans": {
    card_invalid_data: "银行卡信息无效",
    card_number_label: "卡号",
    dialog_continue: "继续",
    map_load_failed: "无法加载地图。请检查网络连接和地图服务设置。",
    payment_failed_message: "付款未完成。请检查银行卡后重试。",
    payment_order_save_error: "无法保存订单。如果已扣款，请联系支持人员。",
    payment_pending_message: "付款仍在处理中。请稍候或重试。",
    payment_verify_error: "无法验证付款。请重试。",
    ux_card_payment_network: "通过 Network International 安全支付",
    ux_change: "更改",
    wallet_amount_exceeds_balance: "金额超过可用余额",
    wallet_card_topup_success: "钱包充值成功。返回钱包吗？",
    wallet_choose_payout: "选择接收资金的银行卡：",
    wallet_withdraw_confirm: "提现",
    wallet_withdraw_description: "从钱包提现",
    wallet_withdraw_no_card_deposit: "没有足以覆盖本次提现的银行卡充值记录",
    wallet_withdraw_refund_failed: "付款退款失败",
    wallet_withdraw_success: "已成功提现 {amount} {currency}",
    map_trip_destination: "行程目的地",
    map_invalid_destinations: "已从路线中排除 {count} 个无效或服务区外的停靠点。",
    checkout_estimated_time_warning: "预计行车时间（{time}）短于建议的预订时长，交通状况可能影响该估算。",
    checkout_vat_rate: "增值税（{rate}%）：",
    map_location_unavailable: "无法获取您的当前位置。",
    map_no_valid_destinations: "此路线没有有效的停靠点。",
    unit_km: "公里", unit_meter: "米", unit_minute: "分钟", unit_hour: "小时", unit_kmh: "公里/小时",
    duration_hours_minutes: "{hours} 小时 {minutes} 分钟",
    location_city_unresolved: "无法准确确定您所在的城市。"
  }
};

const brandValues = {
  en: {
    ux_welcome_login: "Welcome to Touri Taxi",
    ux_welcome_login_sub: "Sign in or create an account to start booking your tour easily",
    app_title: "Touri Taxi"
  },
  ar: {
    ux_welcome_login: "مرحباً بك في توري تاكسي",
    ux_welcome_login_sub: "سجّل دخولك أو أنشئ حساباً لبدء حجز رحلتك السياحية بسهولة",
    app_title: "توري تاكسي"
  },
  ru: {
    ux_welcome_login: "Добро пожаловать в Touri Taxi",
    ux_welcome_login_sub: "Войдите или создайте аккаунт, чтобы легко забронировать поездку",
    app_title: "Touri Taxi"
  },
  ky: {
    ux_welcome_login: "Touri Taxi колдонмосуна кош келиңиз",
    ux_welcome_login_sub: "Сапарыңызды оңой брондоо үчүн кириңиз же аккаунт түзүңүз",
    app_title: "Touri Taxi"
  },
  az: {
    ux_welcome_login: "Touri Taxi-yə xoş gəlmisiniz",
    ux_welcome_login_sub: "Səyahətinizi asanlıqla bron etmək üçün daxil olun və ya hesab yaradın",
    app_title: "Touri Taxi"
  },
  ka: {
    ux_welcome_login: "კეთილი იყოს თქვენი მობრძანება Touri Taxi-ში",
    ux_welcome_login_sub: "მოგზაურობის მარტივად დასაჯავშნად შედით ან შექმენით ანგარიში",
    app_title: "Touri Taxi"
  },
  tr: {
    ux_welcome_login: "Touri Taxi'ye hoş geldiniz",
    ux_welcome_login_sub: "Turunuzu kolayca rezerve etmek için giriş yapın veya hesap oluşturun",
    app_title: "Touri Taxi"
  },
  ur: {
    ux_welcome_login: "Touri Taxi میں خوش آمدید",
    ux_welcome_login_sub: "اپنا سفر آسانی سے بک کرنے کے لیے سائن ان کریں یا اکاؤنٹ بنائیں",
    app_title: "Touri Taxi"
  },
  fr: {
    ux_welcome_login: "Bienvenue sur Touri Taxi",
    ux_welcome_login_sub: "Connectez-vous ou créez un compte pour réserver facilement votre excursion",
    app_title: "Touri Taxi"
  },
  id: {
    ux_welcome_login: "Selamat datang di Touri Taxi",
    ux_welcome_login_sub: "Masuk atau buat akun untuk memesan tur dengan mudah",
    app_title: "Touri Taxi"
  },
  "zh-Hans": {
    ux_welcome_login: "欢迎使用 Touri Taxi",
    ux_welcome_login_sub: "登录或创建账号，即可轻松预订您的旅程",
    app_title: "Touri Taxi"
  }
};

const dir = path.join(__dirname, "..", "assets", "langs");
const countryMapValues = {
  en: "Country map",
  ar: "خريطة الدولة",
  ru: "Карта страны",
  ky: "Өлкөнүн картасы",
  az: "Ölkə xəritəsi",
  ka: "ქვეყნის რუკა",
  tr: "Ülke haritası",
  ur: "ملک کا نقشہ",
  fr: "Carte du pays",
  id: "Peta negara",
  "zh-Hans": "国家地图",
};
for (const file of fs.readdirSync(dir).filter((name) => name.endsWith(".json"))) {
  const locale = path.basename(file, ".json");
  if (!values[locale]) throw new Error(`Missing critical translations for ${locale}`);
  const filePath = path.join(dir, file);
  const current = JSON.parse(fs.readFileSync(filePath, "utf8"));
  const merged = {
    ...current,
    ...values[locale],
    ...brandValues[locale],
    country_map: countryMapValues[locale],
  };
  const updated = Object.fromEntries(
    Object.entries(merged).map(([key, value]) => [
      key,
      typeof value === "string" ? value.replaceAll("Toury Taxi", "Touri Taxi") : value,
    ]),
  );
  fs.writeFileSync(filePath, `${JSON.stringify(updated, null, 2)}\n`, "utf8");
  console.log(`${locale}: synchronized ${Object.keys(values[locale]).length + Object.keys(brandValues[locale]).length} keys`);
}
