/** Stable API error codes for Flutter localization. */
export const PaymentErrorCode = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",
  FORBIDDEN: "FORBIDDEN",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_NOT_OWNED: "BOOKING_NOT_OWNED",
  BOOKING_NOT_PAYABLE: "BOOKING_NOT_PAYABLE",
  ACTIVE_BOOKING_EXISTS: "ACTIVE_BOOKING_EXISTS",
  PAYMENT_ALREADY_EXISTS: "PAYMENT_ALREADY_EXISTS",
  PAYMENT_SESSION_NOT_FOUND: "PAYMENT_SESSION_NOT_FOUND",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_CANCELLED: "PAYMENT_CANCELLED",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  PAYMENT_ACTIVE_OTHER_BOOKING: "PAYMENT_ACTIVE_OTHER_BOOKING",
  PAYMENT_ATTEMPT_EXPIRED: "PAYMENT_ATTEMPT_EXPIRED",
  PAYMENT_NATIVE_UNAVAILABLE: "PAYMENT_NATIVE_UNAVAILABLE",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_CURRENCY_MISMATCH: "PAYMENT_CURRENCY_MISMATCH",
  UNSUPPORTED_CURRENCY: "UNSUPPORTED_CURRENCY",
  INVALID_HOURS: "INVALID_HOURS",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  /** Sandbox/outlet processing config missing at N-Genius (e.g. configFetchError). */
  PROVIDER_OUTLET_NOT_CONFIGURED: "PROVIDER_OUTLET_NOT_CONFIGURED",
  WEBHOOK_INVALID: "WEBHOOK_INVALID",
  REFUND_NOT_ALLOWED: "REFUND_NOT_ALLOWED",
  REFUND_NOT_CONFIGURED: "REFUND_NOT_CONFIGURED",
  NETWORK_ERROR: "NETWORK_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  CONFIG_ERROR: "CONFIG_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type PaymentErrorCode =
  (typeof PaymentErrorCode)[keyof typeof PaymentErrorCode];

export class ApiError extends Error {
  constructor(
    public readonly code: PaymentErrorCode,
    public readonly status: number,
    message?: string,
  ) {
    super(message ?? code);
    this.name = "ApiError";
  }
}
